### ISSUE TITLE
Should wait for server up

### ISSUE THREAD

**Issue by DSigmund** [jprichardson/reload#29]
Wenn killing the Server and restarting it by hand, only the refresh-time is used.
Wait is not used at all.

**Comment by alallier** [comment]
Are you using this in express or are you using the browser development option? What call are you making to reload if using express? What version of reload are you using? Please provide more information when you can :)

**Comment by DSigmund** [comment]
Here is my app.js:

```js
reload = require('reload'),

var timeout = 5000;

reload(server, app, timeout, true);

//start
server.listen(port);
console.log(app.title + "@" + app.version + " running on Port " + port);

```

and my index.html (as jade)
```jade
script(src="/reload/reload.js")
```

And what i do:
I Am just killing the server-process and restart it

**Comment by alallier** [comment]
Thanks for the information, what you brought up is a bug currently waiting to be fixed by PR #27 for now the quick fix it to change your reload line to `reload(server, app, timeout, "true");' Then once the new version comes out the code you posted here should work as expected. Let me know if you have any trouble with the fix I have stated.

**Comment by alallier** [comment]
This issue should be able to be closed now due to Version 0.7.0 being released

**Comment by DSigmund** [comment]
Sry, was busy the last days. I'll check it today

**Comment by DSigmund** [comment]
OK, works now :-)
