### ISSUE TITLE
The front end view lib file issue

### ISSUE THREAD

**Issue by dotku** [jprichardson/reload#35]
I add reload to my front end file

    <script src="/lib/reload/reload.js"></script>

It says requirejs is not defined, so I use `bower installed requirejs`, and place requirejs before reload, and finally I got this

    Uncaught Error: Module name "sockjs" has not been loaded yet for context: _. Use require([])

**Comment by alallier** [comment]
Use `<script src="/reload/reload.js"></script>` not 

> `<script src="/lib/reload/reload.js"></script>`

**Comment by dotku** [comment]
@alallier it would be a 404 error, I'm using Express 4.13.1. The front end can access only /public folder, I copy /reload/ folder to /public/lib for access

**Comment by alallier** [comment]
If you inspect on the browser do you see the reload.js file?

**Comment by dotku** [comment]
Yes, it is there, i copy the reload.js from npm folder `node_modules` to my /public/lib foulder, so it can be visiable. There is no 404 error.

**Comment by alallier** [comment]
You shouldn't have to do that unless I am overlooking something, what happens when you add `<script src="/reload/reload.js"></script>`

**Comment by dotku** [comment]
@alallier /reload/ can't be found, you can checkout the code here: https://github.com/dotku/node-study

**Comment by alallier** [comment]
I'm looking at your code now, give me a bit to ponder and play with this.

**Comment by alallier** [comment]
Update on this, I was able to get reload working with the proper script tag `<script src="/reload/reload.js"></script>`. The problem was you declared reload too far down in your app.js and it wasn't creating the proper route. You don't need reload and sockjs files in your `public/lib` directory. You can check out the changes in my fork [here](https://github.com/alallier/node-study). Now I seem to be running into an issue like #30. So i'm looking into that, hope to have you up and running without problems soon.

**Comment by alallier** [comment]
So upon further investigation, there seems to be some issue with sockjs and chrome. I tried running my fork of your project with Firefox and it worked as expected. I'll continue to look into this, investigate, and work with sockjs. I recommend you close the issue you filed with sockjs since the bug you were discussing  was on reload's end and we solved that issue.

**Comment by dotku** [comment]
@alallier yes, please close the issue :)

**Comment by alallier** [comment]
You got this working?

**Comment by dcsan** [comment]
```js
// hot reloading
var reload = require('reload');
var reloader           = require('http').Server(app);
reload(reloader, app, 300);

reloader.listen( app.get('port'), function() {
  console.log('listening on port ' + app.get('port'));
});
```

ref issue   https://github.com/jprichardson/reload/issues/36

**Comment by alallier** [comment]
Closing for now, please check out the new version (1.0.0) and see if this still is an issue. If it is please re-open the issue. Also, I recommend checking out the [express sample app](https://github.com/jprichardson/reload/tree/master/expressSampleApp) to get a better idea of how reload works.
