### ISSUE TITLE
Add macOS CI

### ISSUE THREAD

**Issue by yamboy1** [jprichardson/reload#96]
I think that it's a good idea to add a CI to make macOS builds. I've found [CircleCI](https://github.com/marketplace/circleci) which says that it can build for macOS, but I havn't had a chance to test it.

**Comment by alallier** [comment]
Is CircleCi Travis's main "_competitor_ " (for a lack of better word, since they are both free)? Since Travis is executing in the bash environment doesn't Travis cover the build for Linux and Mac (assuming no Mac specific commands)? More thoughts on this would be useful when you've tested things out, let us know. Thank you!

**Comment by jprichardson** [comment]
Travis can do `macOS` as well: https://docs.travis-ci.com/user/osx-ci-environment/

**Comment by yamboy1** [comment]
I was just looking at that now. I will do a test in one of my repos to see how it works.

**Comment by yamboy1** [comment]
All you need to do is tell it to use both macOS and Linux. I've created a pull request #97.

**Comment by yamboy1** [comment]
I've  created another pull request with only 1 commit. #98

**Comment by yamboy1** [comment]
Mac builds take a while to start building. Have a look at the build for #98. https://travis-ci.org/jprichardson/reload/builds/243761480. There is about 10 minutes spent waiting for the osx builds to start. I am going to see if using CircleCI would be faster.

**Comment by alallier** [comment]
Closed by #98

**Comment by alallier** [comment]
I'm almost thinking of backing out mac os building as it **really** slows the building process down.

See: https://github.com/travis-ci/travis-ci/issues/7304

**Comment by AckerApple** [comment]
I recommend removal. I can't think of a command on Linux that doesn't work on Mac. All my deployments are from Mac onto Linux. I added Mac to my ack-reload fork and am set to delete it as well for the long times. Farewell fellas, impressing me to see such big ticket items being tackled day after day.

**Comment by yamboy1** [comment]
@alallier What are we doing about this. Should we remove Mac CI support completely? Or maybe go with my original idea of using CIrcleCI? I've seen a couple of projects which use both Travis and Circle. Maybe we should do that.

**Comment by alallier** [comment]
Not sure we have no research on CircleCI but I over waiting for Travis Mac VMs to spin up, it just takes way too long, since they are a limited resource

**Comment by yamboy1** [comment]
@AckerApple What did you do about this?

**Comment by AckerApple** [comment]
Thanks for asking. I completely removed for two reasons (have not pushed to NPM yet):

#1 : Mac runs on the same "rails" as Linux so they 99.9% produce the same results
#2 : The travis cli tester waits forever to start and then when it says started it still has a ton of MAC startup commands processing

You fellas have been working hard on this project. I think I might jump back in with y'all. I would add what's already in my fork:

#1 If port is already taken the reload wants to use, offer cli prompt to go to next port
#2 A true NPM test with unit test cases (describe, it, assert)
#3 Remove express (I don't use "your" reload because of this)

Thanks for asking my opinion

**Comment by alallier** [comment]
Thanks for your comment @AckerApple but please keep the conversation limited to the topic of this issue. Personally I think it might just be worth removing MacOS building for now as we are really just linting now and that makes no difference when running on Linux vs MacOS. The only reason I would be hesitant is I am planning to write unit tests next for this and building on Mac then would make a difference. But for now we could consider removing MacOS and adding it back when unit testing is added (knowing the performance problems or looking at an alternative like CircleCI).

Do we have any idea if CircleCI's Mac building is _way_ faster that Travis's? If it isn't it's not worth adding

**Comment by AckerApple** [comment]
@alallier . Seriously man? "Please keep the conversation limited to the topic of the issue".

Please keep being a Robot to a minimum and take these chances to be alive.

Whatever, I couldn't really read the rest when you act like Angular with comment control policing like we don't have time to be considerate to be humans.

And I don't have a filter. My fault.

**Comment by alallier** [comment]
If you have a new idea or suggestion please open an issue and we can discuss it there.
